on: [pull_request]

name: R-CMD

jobs:
  R-CMD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} 

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest }

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('distill','rmarkdown','renv'))"
          
      - name: Render Rmd files from _posts
        run: |
          Rscript rscript.R

      - name: Commit files  
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./docs
          git commit -m "updated site"
          